function Hd = bandstop(x)
%BANDSTOP 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 21-Nov-2023 20:08:50

% Butterworth Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 50;  % Sampling Frequency

N   = 4;    % Order
Fc1 = x-0.01;  % First Cutoff Frequency
Fc2 = x+0.01;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandstop('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
