function Hd = IIR_heart
%IIR_HEART 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 20-Nov-2023 14:34:10

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 50;  % Sampling Frequency

N   = 8;    % Order
%0.8~2.0
Fc1 = 0.8;  % First Cutoff Frequency
Fc2 = 2.0;    % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
